# TensorFlow Basics

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.15.0


## Tensors

In [0]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [0]:
world = tf.constant('World')

In [0]:
result = hello + world

In [7]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [8]:
type(result)

tensorflow.python.framework.ops.Tensor

In [0]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [10]:
result

b'HelloWorld'

**Computations**

In [0]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [12]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [13]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
sess

In [0]:
sess.close()

## Operations

In [0]:
const = tf.constant(10)

In [0]:
fill_mat = tf.fill((4,4),10)

In [0]:
myzeros = tf.zeros((4,4))

In [0]:
myones = tf.ones((4,4))

In [0]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [0]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [0]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [0]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [24]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.84488213 -0.14671259  0.48219392  0.07293254]
 [ 0.10120542  0.7077379   0.15651898 -0.40191284]
 [ 0.9496361   0.35173935  0.78843766 -0.12703824]
 [-1.1044824  -1.1417813   0.57258356 -0.2362017 ]]


[[0.5534471  0.22846925 0.46180356 0.80299973]
 [0.14883602 0.3072784  0.7886574  0.5915749 ]
 [0.22780132 0.3647033  0.38866484 0.69918346]
 [0.9664992  0.10375988 0.5434265  0.18460023]]




## Matrix Multiplication

In [0]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [26]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [0]:
b = tf.constant([[10],[100]])

In [28]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [0]:
result = tf.matmul(a,b)

In [30]:
result.eval()

array([[210],
       [430]], dtype=int32)